name: Backend CI
on: [push, pull_request]

jobs:
  TEST_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: BUILD and TEST with Maven
        run: mvn install

      - name: Test coverage > 80% ?
        run: mvn jacoco:check

#      - name: Sonarqube test coverage
#        run: ./mvn sonar:sonar
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Artifact [kotlin-maven-1.0]
        uses: actions/upload-artifact@v1
        with:
          name: kotlin_maven-1.0.jar
          path: target/kotlin_maven-1.0.jar
